### ISSUE TITLE
Presentation Mode RemNote Plugin

### ISSUE THREAD

**Issue by bnleez1** [bjsi/presentation-mode#1]
I know it should be obvious, but I read under "How To Use" the following: "Focus the parent and run the "Start Presentation" command.

Not sure what "Focus the parent" means and not sure what is meant by, "... run the "Start Presentation" command. Where do I find such a command?

**Comment by bjsi** [comment]
Hey @bnleez1 I replied on Twitter here:

![image](https://user-images.githubusercontent.com/58147075/201707941-4ee49269-8a0a-4c20-b635-23152733edf8.png)

Please let me know if you run into any other issues!
